### ISSUE TITLE
Passthrough SIGTERM to borg when the container receives it

### ISSUE THREAD

**Issue by BBaoVanC** [borgmatic-collective/docker-borgmatic#104]
I want to be able to stop all my services in my docker compose project at once, but borgmatic seems to ignore the SIGTERM and wait for the backup to complete (which might take a while). I think it should be passed down to borg, so it can safely stop the backup without leaving a lock behind or creating a broken backup.

As far as I can tell, Ctrl-C seems to work with borg itself so I imagine there must be some way to make this work.

**Comment by grantbevis** [comment]
Have you read the README section regarding sending docker commands to the docker engine's API?

**Comment by BBaoVanC** [comment]
All I see is a section titled "Starting and stopping containers from hooks" which isn't what I want

**Comment by psi-4ward** [comment]
This is a good point I've stumbled over.

We should introduce a `trap` and forwarding SIG(TERM|INT|KILL) to a potentiell running borg process and wait for it's termination and not only exit cron. I'll could try to prepare a PR

**Comment by BBaoVanC** [comment]
> I'll could try to prepare a PR

That would be great! This is really important to me since I've had many times where I updated the containers and didn't realize it was creating a backup, so I ended up with a broken lock (and then missed a day of backups before I notice the issue).

**Comment by psi-4ward** [comment]
@BBaoVanC 
Pls test: https://github.com/psi-4ward/docker-borgmatic/pkgs/container/borgmatic

**Comment by grantbevis** [comment]
This will be fixed under #173
