### ISSUE TITLE
Request to add logrotate to docker image

### ISSUE THREAD

**Issue by Sdub76** [borgmatic-collective/docker-borgmatic#111]
I use the logging feature in Borgmatic, but currently have to deal with log rotation in a cron script on the host.  It would be much simpler and more self-contained if you could add this common utility to the borgmatic docker image.

**Comment by grantbevis** [comment]
Just to confirm; You’d like logrotate added to the image? 

Unless you’re running logrotate manually I don’t think it’s in the scope of this project to add in default log management

**Comment by Sdub76** [comment]
Yes, I'm using the --log-file option in borgmatic to write log output to a file, but this only appends, and the log file gets infinitely large.  This is exactly what logrotate is for and is directly tied to managing the logs associated with the borgmatic container.  

Most projects handle rotating logs within their own context, and don't require a separate cron job to rotate their logs for them... hence why I think it should be considered in-scope for this container.

Right now, my crontab looks like "
`ssh user@docker-host logrotate /path/to/config-on-host && borgmatic --opts `

It would be a lot more straightforward to have
`logrotate /path/to/config-in-container && borgmatic --opts `

**Comment by grantbevis** [comment]
I agree in this case, I will raise a PR and have the package added to the image

**Comment by grantbevis** [comment]
Fixed, please wait for the new image to be built and retest using the :latest tag

**Comment by Sdub76** [comment]
Worked perfectly. Thanks!
