### ISSUE TITLE
Change version tags for new releases

### ISSUE THREAD

**Issue by grantbevis** [borgmatic-collective/docker-borgmatic#120]
I think it would be more beneficial if the image tag follows the borgmatic semver and we state in the readme that we will always follow the latest borgbackup package at time of borgmatic release.

instead of borgmatic:v1.2.0-1.6.1 -> borgmatic:1.6.1

thoughts @witten ?

**Comment by witten** [comment]
Makes sense to me!

**Comment by grantbevis** [comment]
This will be implemented as part of #119
