### ISSUE TITLE
Docker account rename/convert

### ISSUE THREAD

**Issue by grantbevis** [borgmatic-collective/docker-borgmatic#125]
It's possible to convert my personal docker hub account into an organisation and possibly rename. This will need to be communicated to users if we were to go down this path. No issues with it being on my docker hub account, I'm just thinking for consistency it should be under the 'borgmatic-collective' moniker than b3vis.

![image](https://user-images.githubusercontent.com/20246437/171371810-2afb0187-260f-4e49-9350-cc44b2e9be3c.png)

Thoughts @witten

**Comment by grantbevis** [comment]
It doesn't look like it no: https://hub.docker.com/support/doc/how-do-i-convert-my-docker-hub-user-account-into-an-organization-account

What we could do is create the organisation on docker hub and we can setup the CI to push images to b3vis/borgmatic and borgmatic-collective/borgmatic and put up a deprecation notice to the b3vis/borgmatic image tag. I will have a look

**Comment by grantbevis** [comment]
Also @witten - There's no issue with this using my docker hub account, I was just thinking its time it changed to do things properly

**Comment by witten** [comment]
Personally, I think it's fine to "break" the b3vis/borgmatic Docker URL.. ideally with a deprecation notice in place, but even that is a nice-to-have IMO.

When this is done I can change the link from the borgmatic docs, so that should at least tell some users where to go.

**Comment by grantbevis** [comment]
Seems like Docker charge to create a new Organisation, $7 per user... I've applied for their open source program on our behalf. Lets see where this goes.

**Comment by witten** [comment]
Hope that works! I'd be happy to host a separate registry, but I recognize that makes discoverability and installs more difficult.

**Comment by grantbevis** [comment]
I have got the image hosted right here on this repo too: https://github.com/borgmatic-collective/docker-borgmatic/pkgs/container/docker-borgmatic

`docker pull ghcr.io/borgmatic-collective/docker-borgmatic:latest`

**Comment by grantbevis** [comment]
^ This isn't public though - I will switch that over now

**Comment by grantbevis** [comment]
I'm unable to change the setting @witten: https://github.com/orgs/borgmatic-collective/packages/container/docker-borgmatic/settings - at the bottom 'Change Visibility'

**Comment by witten** [comment]
I just changed the organization package creation settings here: https://github.com/organizations/borgmatic-collective/settings/packages

Not sure if you have perms to change those. If not, you should!

Anyway, maybe try again at: https://github.com/orgs/borgmatic-collective/packages/container/docker-borgmatic/settings

**Comment by grantbevis** [comment]
Doh, I forgot I was an org admin 😆 - I've set the package to be public and I can pull it unauthenticated.

I will see if I can rename the package so it's just 

docker pull ghcr.io/borgmatic-collective/borgmatic:latest

**Comment by grantbevis** [comment]
#128 solves the package rename so images will be `ghcr.io/borgmatic-collective/borgmatic:$tag`

**Comment by grantbevis** [comment]
This has worked @witten 
`docker pull ghcr.io/borgmatic-collective/borgmatic:latest`

https://github.com/borgmatic-collective/docker-borgmatic/pkgs/container/borgmatic/24936971?tag=latest

I've just re-released 1.6.3 here so it'll build a :1.6.3 image - Once that's up I'll edit the README and other examples to point to use the GitHub docker repository

**Comment by modem7** [comment]
@grantbevis - I'm just going through the issues - should we close this off?
