### ISSUE TITLE
Alpine 3.16 build failure

### ISSUE THREAD

**Issue by grantbevis** [borgmatic-collective/docker-borgmatic#140]
https://github.com/borgmatic-collective/docker-borgmatic/runs/7412311132?check_suite_focus=true

Since merging #139 it's failing to build - @modem7 it's moaning about missing things from the pypi cache, any ideas bud?

**Comment by modem7** [comment]
> https://github.com/borgmatic-collective/docker-borgmatic/runs/7412311132?check_suite_focus=true
> 
> Since merging #139 it's failing to build - @modem7 it's moaning about missing things from the pypi cache, any ideas bud?

Already on it!

Will let you know once the pypi cache rebuilds (shouldn't take too long).

**Comment by modem7** [comment]
@grantbevis - looks like there was a typo in the gh-pages generation. 

Please re-run the build again.

**Comment by modem7** [comment]
Looks like build is now working as expected. 

Will close issue for now.
