### ISSUE TITLE
/usr/bin path changed to /usr/local/bin

### ISSUE THREAD

**Issue by Skydiver84de** [borgmatic-collective/docker-borgmatic#149]
Hi,
After the latest update I realised that borgmatic was no longer triggered by the crontab. As crontab is calling /usr/bin/borgmatic and outputs a file not found error, I checked inside the container and found out that borgmatic as well as borg, borgfs and other binaries are located in /usr/local/bin now which explains why the crontab fails to run. 

Is this by intention and The crontab needs to be adapted?

KR
Mario

**Comment by DBendit** [comment]
I assume this is caused by https://github.com/borgmatic-collective/docker-borgmatic/pull/148

**Comment by grantbevis** [comment]
This is correct and caused by #148 - I've updated the example here https://github.com/borgmatic-collective/docker-borgmatic/blob/master/base/data/borgmatic.d/crontab.txt

Apologies for this issue, this is necessary to optimise our docker image building

FYI @modem7

**Comment by modem7** [comment]
@grantbevis Tbf, we shouldn't need the paths as Borgmatic + Borg are already in the system paths.

```
/ # docker exec -it Borgmatic sh

/ # echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/ #
```

So by just having this in the cron file, it should work regardless:
```
0 5 * * * borgmatic --stats -v 0 2>&1
```

![image](https://user-images.githubusercontent.com/4349962/185425182-ffcb7d7c-f573-4488-8a20-2ce9e2f35bc8.png)

**Comment by grantbevis** [comment]
Yessssss that’s right! Adding the path at the beginning was a hack from yonks ago. Stupid me.

will get it tidied soon

**Comment by modem7** [comment]
> Yessssss that’s right! Adding the path at the beginning was a hack from yonks ago. Stupid me.
> 
> will get it tidied soon

I'm just working on something better than a separate file, it's dumb, and we should be using env vars. 

Bear with me, should be done in a bit and I'll submit a PR once I'm happy it's working!
