### ISSUE TITLE
Add REQUESTS_CA_BUNDLE environment variable to image

### ISSUE THREAD

**Issue by barry-luijten** [borgmatic-collective/docker-borgmatic#154]
When using self-hosted versions of healthchecks or ntfy _and_ using self-signed certificates for those services, you probably want to add your local CA certificate to the trusted CA bundle file. Usually, that bundle file is mounted in /etc/ssl/certs/ca-certificates.crt.
The Python "requests" package seems to use its own CA bundle, which can be overridden by setting an environment variable named REQUESTS_CA_BUNDLE.
Setting this variable in Dockerfile to the OS-default would be more intuitive imho. In the case of Alpine (the base image of borgmatic-docker), this should be:
`ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt`

See also: https://stackoverflow.com/a/42982144/6914194

**Comment by grantbevis** [comment]
This isn't something I want to manage as part of the image, sorry.
