### ISSUE TITLE
ntfy not found

### ISSUE THREAD

**Issue by tomtjes** [borgmatic-collective/docker-borgmatic#157]
With the latest container, the borgmatic log says:
`/bin/sh: ntfy: not found`

When call ntfy from the console, I get
`bash: /usr/bin/ntfy: /usr/bin/python3: bad interpreter: No such file or directory`

Seems like python has been moved to `/usr/local/bin/python3`

**Comment by ericswpark** [comment]
A symlinking step from /usr/local/bin to /usr/bin should fix this, and would also fix old crontab.txts not finding the borgmatic executable as a side effect.

**Comment by grantbevis** [comment]
ntfy is deprecated in this image as we're switching to apprise

**Comment by ericswpark** [comment]
@grantbevis is `apprise` already included in the base image?

**Comment by modem7** [comment]
> @grantbevis is `apprise` already included in the base image?

Heya, that it is.

apprise==1.1.0
