### ISSUE TITLE
Wrong path in BACKUP_COMMAND

### ISSUE THREAD

**Issue by newpipe** [borgmatic-collective/docker-borgmatic#162]
The path to the "BACKUP_COMMAND" is wrong in the file
https://raw.githubusercontent.com/borgmatic-collective/docker-borgmatic/master/msmtp/data/scripts/env.sh

Correct would be:
BACKUP_COMMAND="/usr/local/bin/borgmatic --stats"

The "/local" is missing.

**Comment by Coronon** [comment]
YES! This is failing all my backups with the current version

**Comment by newpipe** [comment]
Thank you!
