### ISSUE TITLE
Add '--domain' flag for sendmail

### ISSUE THREAD

**Issue by Sakorah** [borgmatic-collective/docker-borgmatic#175]
With the msmtp image, sendmail issues a EHLO/HELO to a remote SMTP server and may falls back using 'localhost'. SMTP servers will reject maybe localhost or if the presented hostname is not a FQDN:
```
504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname
```
By adding the --domain flag to sendmail it is possible to explicitly set the presented hostname.

**Comment by modem7** [comment]
As per https://github.com/borgmatic-collective/docker-borgmatic/issues/157 we're moving to Apprise instead of msmtp as it's outdated. Please adjust your commands to the appropriate apprise config syntax.
