### ISSUE TITLE
MySQL Server > 8 Authentication plugin ‘caching_sha2_password’ cannot be loaded

### ISSUE THREAD

**Issue by AndreasMurk** [borgmatic-collective/docker-borgmatic#176]
Hi!

I am having problems making a dump from a mysql server with version `8.0.29`

The problem is that as soon the command `mysqldump --add-drop-database --host somehost -u root --databases somedb > dump.sql` runs, it will give the error 

```
MYSQL ERROR 2059 (HY000): Authentication plugin ‘caching_sha2_password’ cannot be loaded: /usr/lib64/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
```
After researching, I have found out that MySQL has changed the `native_password` authentication to `caching_sha2_password`.
When looking at the `DOCKERFILE`, the `mariadb-client` will be installed using apk command.

However, after installing the `mariadb-connector-c` package, everything runs smoothly.

Do other people encountered this problem?

If so, would it be possible to add this package to the `DOCKERFILE`?

Thank you!

**Comment by kisamoto** [comment]
Confirmed both the problem and the fix (installing `mariadb-connector-c`)

**Comment by AndreasMurk** [comment]
I wanted to create a PR, but I was not able to. 

Would definitely appreciate if this would be fixed asap.
Otherwise, I can also create the PR and propose the fix for it but I don't know how to create the correct PR.

Thank you guys!
