### ISSUE TITLE
SELinux restore compatibility

### ISSUE THREAD

**Issue by ThorpeJosh** [borgmatic-collective/docker-borgmatic#179]
The [docker-compose.restore.yml](https://github.com/borgmatic-collective/docker-borgmatic/blob/master/base/docker-compose.restore.yml) file makes specific reference to [apparmor](https://github.com/borgmatic-collective/docker-borgmatic/blob/e87ed9009e3c0f7426aee8fce3ff6369cf2bc916/base/docker-compose.restore.yml#L10). I haven't tested yet but I presume this will not work on SELinux hosts. I believe it will need to be `privileged` instead.

What is the best way to add compatibility for non-apparmor distros?

**Comment by modem7** [comment]
Unsure - I can take a look, but I use a VM with Vorta to do any restores rather than Docker itself.

**Comment by ThorpeJosh** [comment]
Thanks for the responses and suggestions.

@modem7, My latest SELinux docker hosts have been Fedora and Rocky. Docker does behave a bit differently to my Debian based hosts.

**Comment by modem7** [comment]
> Thanks for the responses and suggestions.
> 
> @modem7, My latest SELinux docker hosts have been Fedora and Rocky. Docker does behave a bit differently to my Debian based hosts.

Have you tried reading https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label and see if it helps?
