### ISSUE TITLE
borgmatic check state persistence

### ISSUE THREAD

**Issue by witten** [borgmatic-collective/docker-borgmatic#211]
As of borgmatic 1.7.0, [borgmatic stores check state](https://torsion.org/borgmatic/docs/how-to/deal-with-very-large-backups/#check-frequency) in `~/.borgmatic/checks`, which allows the user to configure checks to run on a rough schedule instead of every time borgmatic runs. There is also a default schedule that relies on `~/.borgmatic/checks` even if the user doesn't configure anything.

So do you think it makes sense for the Docker image documentation to instruct the user to mount this path as a volume? That way the check state would be persisted across restarts of the container. I realize I was probably the one who told you that `~/.borgmatic` doesn't need persisting anymore, so I take responsibility for this even being an issue with the Docker image to begin with!

Tangentially related issue: https://projects.torsion.org/borgmatic-collective/borgmatic/issues/562

**Comment by grantbevis** [comment]
No worries @witten I'll get a PR ready to persist `~/.borgmatic`

**Comment by witten** [comment]
It looks like `~/.borgmatic` is no longer in the [Docker Compose file](https://github.com/borgmatic-collective/docker-borgmatic/blob/master/docker-compose.yml)...?

**Comment by witten** [comment]
An update: With borgmatic 1.9.0, check states have been moved out of `~/.borgmatic/checks` to `~/.local/state/borgmatic/checks`. It may still be worth looking into whether they should be persisted across borgmatic container runs (via a host-mounted volume).

**Comment by witten** [comment]
About to be implemented (if it gets merged) by #364.
