### ISSUE TITLE
arm/v7 support dropped?

### ISSUE THREAD

**Issue by witten** [borgmatic-collective/docker-borgmatic#215]
It looks like with [the most recent release (1.7.8) on Docker hub](https://hub.docker.com/r/b3vis/borgmatic/tags), there are only builds for `amd64` and `arm64`. Whereas previous releases (e.g. 1.7.7) included support for `arm/v6` and `arm/v7`. I just wanted to confirm whether this was intentionally dropping support for those architectures...? Thanks!

**Comment by witten** [comment]
Oh, looks like the answer might be yes! https://github.com/borgmatic-collective/docker-borgmatic/pull/214

**Comment by grantbevis** [comment]
Yes, we’ve intentionally dropped support for 32bit ARM build’s because it was causing a headache

Is this an issue @witten ? Apologies if so
