### ISSUE TITLE
Backup restore suggestion

### ISSUE THREAD

**Issue by Spider-One** [borgmatic-collective/docker-borgmatic#217]
I was having a bit of trouble restoring my backup as a test. I think the intention was to mount inside the container and restore to the source folder? I found the README `borg mount /mnt/borg-repository <mount_point>` command unclear regarding to what I would choose for the mount point inside the container. I found I could add a mount volume and a restore point to make it work but wasn't sure if that was the ideal method as it seemed to only allow for restoring an entire archive? Would be helpful to detail the few extra steps but I didn't want to create a PR not actually knowing the ideal process to restore.

As another option is you add a volume to the docker-compose.restore.yml shown below. Then `borg mount /mnt-repository /restore`

```
volumes:
  - /mnt/restore:/restore:shared
```

The :shared tag allows host access to the mounted files on the /mnt/restore point so they could be copied on the host if needed. Really handy if you're only looking for a particular file?

**Comment by grantbevis** [comment]
Could you please clarify your request? I don't understand what you would like from us
