### ISSUE TITLE
Update to Borgmatic 1.7.10

### ISSUE THREAD

**Issue by coffeepenbit** [borgmatic-collective/docker-borgmatic#224]
Hi,

Thanks for all your work on this Docker image; it's incredibly useful.

Borgmatic came out with a 1.7.10 version that introduces a few cool features (one being the use of constants in YAML files) which I'm keen to use.

Would it be possible to update the Borgmatic image to use version 1.7.10+?

Thanks

**Comment by grantbevis** [comment]
Hi,

We held off upgrading to 1.7.10 as there was a bug reading configuration files. I've just merged this to update to 1.7.11 which has the new feature and bug fix

https://github.com/borgmatic-collective/docker-borgmatic/pull/223

**Comment by coffeepenbit** [comment]
Thank you!!!
