### ISSUE TITLE
[msmtp] Not using MAIL_SUBJECT

### ISSUE THREAD

**Issue by rallisf1** [borgmatic-collective/docker-borgmatic#242]
Borgmatic Version: 1.7.15

Mails get sent fine but only have `✅ SUCCESS:` or `❌ FAILED:` as subject without the value of `MAIL_SUBJECT`

**Comment by Psycho0verload** [comment]
@rallisf1 have a look at #228.
That MSMTP has been removed is not a big deal. You can easily replace it with apprise.

As cronjob you set the following:
```
*/5 * * * * PATH=$PATH:/usr/local/bin /usr/local/bin/borgmatic --stats -v 0 > /tmp/backup_run.log
```
This will write the output of Borgmatic to the log file and then send it away via apprise
```
before_backup:
  - echo "Starting a backup job."
after_backup:
  - echo "Backup created."
  - apprise -vv -t "your-subdomain.example.com - BorgBackup" -b "$(cat /tmp/backup_run.log)" "mailtos://smtp.example.com:587?user=info@example.com&pass=YourSecurePassword&from=server@example.com"
on_error:
  - echo "Error while creating a backup."
```
