### ISSUE TITLE
Upgrade mongodb-tools package version

### ISSUE THREAD

**Issue by tmm360** [borgmatic-collective/docker-borgmatic#255]
Current image uses mongodb-tools-4.2.14-r17 that is a very old version.

This breaks compatibility with newer mongodb versions (see for example here: https://www.mongodb.com/community/forums/t/user-with-root-role-cannot-access-config-database/9693/5)

Upgrade base image to `python:3.11.4-alpine3.18` solves the problem.

**Comment by modem7** [comment]
We're now at 3.11.5-alpine3.18
