### ISSUE TITLE
Not able to receive email notifciations

### ISSUE THREAD

**Issue by kiekar** [borgmatic-collective/docker-borgmatic#293]
Current installation:  Borgmatic 1.8.5, Borg 1.2.7 and apprise 1.6.0

**current conf.yaml entry**

`source_directories:
    - /mnt/source
    - /mnt/source/vmail
repositories:
    - path: /mnt/borg-repository
      label: local
exclude_patterns:
    - '/mnt/source/postfix/public/'
    - '/mnt/source/postfix/private/'
    - '/mnt/source/rspamd/rspamd.sock'

keep_hourly: 24
keep_daily: 7
keep_weekly: 4
keep_monthly: 6

mysql_databases:
    - name: mailcow
      username: mailcow
      password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      options: --default-character-set=utf8mb4

before_backup:
  - echo "Starting a backup job."

after_backup:
  - apprise -vv -t "SUCCESS" -b "Backups successfully made" "mailto://mail.mydomain.com:587?user=user1@mydomain.com&pass=xxxxxx&from=user2@mydomain.com"`

**Output**

apprise -vv -t "SUCCESS" -b "Backups successfully made" "mailto://mail.mydomain.com:587?user=user1@mydomain.com&pass=xxxxx&from=user2@mydomain.com"
2024-01-25 10:56:26,325 - INFO - Applying Custom Defaults
2024-01-25 10:56:26,559 - WARNING - Connection error while submitting email to mail.centuryit.com. Reason: [Errno 101] Network unreachable
local: Error running actions for repository
Command 'apprise -vv -t "SUCCESS" -b "Backups successfully made" "mailto://mail.mydomain.com:587?user1=user1@mydomain.com&pass=xxxxxx&from=user2@mydomain.com"' returned non-zero exit status 1.
/etc/borgmatic.d/config.yaml: No commands to run for on-error hook
/etc/borgmatic.d/config.yaml: An error occurred
/etc/borgmatic.d/config.yaml: No commands to run for post-everything hook

summary:
/etc/borgmatic.d/config.yaml: Loading configuration file
/etc/borgmatic.d/config.yaml: An error occurred
local: Error running actions for repository
2024-01-25 10:56:26,325 - INFO - Applying Custom Defaults
2024-01-25 10:56:26,559 - WARNING - Connection error while submitting email to mail.mydomain.com. Reason: [Errno 101] Network unreachable
Command 'apprise -vv -t "SUCCESS" -b "Backups successfully made" "mailto://mail.mydomain.com:587?user=user1@mydomain.com&pass=xxxxx&from=user2@mydomain.com"' returned non-zero exit status 1.

Need some help? https://torsion.org/borgmatic/#issues

Never receive postfix logs

**Comment by grantbevis** [comment]
> 2024-01-25 10:56:26,559 - WARNING - Connection error while submitting email to mail.mydomain.com. Reason: [Errno 101] Network unreachable

there’s your problem, can you hit the mail server from your container?

**Comment by grantbevis** [comment]
Ping != mailflow but it's a start. I'd check you can access port 587 too, This is a user issue and nothing to do with borgmatic or the image so closing this.
