### ISSUE TITLE
Add rclone to image

### ISSUE THREAD

**Issue by tuetenk0pp** [borgmatic-collective/docker-borgmatic#304]
I would like to use rclone to sync my backups to a remote using the `after_everything:` mechanism. Let me know if you would approve a PR adding rclone to the image and I will happily make one. I already did some testing here: https://github.com/tuetenk0pp/borg-rclone

**Comment by modem7** [comment]
As per https://github.com/borgmatic-collective/docker-borgmatic/pull/284#issuecomment-1872883902 we don't want to add additional packages to the image that may bloat it. 

In future, we'll probably add a variable that will install additional packages that can be user populated, but for now, it's not in scope.

Closing as not (directly) planned.
