### ISSUE TITLE
on_error and Apprise causing Borgmatic to fail backups

### ISSUE THREAD

**Issue by ericswpark** [borgmatic-collective/docker-borgmatic#306]
Here is the `on_error` hook I was using:

```
on_error:
  - apprise --title="Borgmatic" --body="An error occurred.\n{error}\n{output}" -e
```

It was working fine, until an update to borgmatic broke it. Now it fails with the following output:

```
/etc/borgmatic.d/config.yaml: Error running on-error hook
Usage: apprise [OPTIONS] SERVER_URL [SERVER_URL2 [SERVER_URL3]]
Try 'apprise -h' for help.
Error: No such option: --keep-daily
Command 'apprise --title="Borgmatic" --body="An error occurred.\n'Command '"'"'borg prune --keep-daily 7 --keep-hourly 24 --keep-monthly 6 --keep-yearly 5 --glob-archives server-1-* --stats --info --list ssh://borg@server-2/./server-1.borg'"'"' returned non-zero exit status 2.'\n'...
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 368, in open
(...)
```

It seems like the `{error}` variable does some quote escaping, which manages to escape out of the `--body=""` quotes.

**Comment by witten** [comment]
This looks like a borgmatic issue and not an issue with the Docker container. I recommend filing it here instead: https://torsion.org/borgmatic/#issues

Thank you!

**Comment by ericswpark** [comment]
@witten just transferred, closing this issue. Thanks and sorry for filing it in the wrong place.

**Comment by witten** [comment]
Thank you! It's not a problem at all.
