### ISSUE TITLE
Install xxhash to support borgmatic's new "spot" check

### ISSUE THREAD

**Issue by witten** [borgmatic-collective/docker-borgmatic#314]
borgmatic 1.8.10 adds a new ["spot" check](https://torsion.org/borgmatic/docs/how-to/deal-with-very-large-backups/#spot-check), but it requires the `xxhash` package to be installed in order to work. So if you want to support this consistency check within docker-borgmatic, you may want to add this package to your image!

**Comment by grantbevis** [comment]
Solved in https://github.com/borgmatic-collective/docker-borgmatic/pull/316

**Comment by witten** [comment]
Thanks!
