### ISSUE TITLE
Documentation improvement for Docker control before/after backup

### ISSUE THREAD

**Issue by Bubbelb** [borgmatic-collective/docker-borgmatic#343]
Hi there, 

Since a few days I have been toying with the docker container of borgmatic. I found a few (small) things I think are worth noting in the Readme to get others started:

1. The Environment variable ```DOCKERCLI='true'``` needs to be set on your docker command line, or compose.yaml, the docker client executables are being installed, which helps a great deal controlling containers.
2. With that, of course a bind mount must exist as follows: ```/var/run/docker.sock:/var/run/docker.sock```
3. To stop and start containers, I did the following in the config file:
```
...
constants:
  ...
  containernames: "container-a container-b container c"
...
before_backup:
  - echo {containernames} | xargs docker stop

after_backup:
  - echo {containernames} | xargs -n 1 echo | tac | xargs docker start
...
```
This way all the containers are stopped in order before the backup and restarted in reverse order after the backup. This way, for instance, you can ensure the back-end gets stopped last and started first.

Hope this helps someone :)

**Comment by callumhauber** [comment]
Thank you! I was having issues with using the REST API from the readme. I could stop a container, but starting a container was giving me "context canceled."

With `DOCKERCLI='true'` & `docker start/stop {container}` everything is working how it should

**Comment by kevnikos** [comment]
Thanks for this!  This should definitely be the recommendation.  I have 26 containers!  It was failing to restart for me as well.  I'm using a compose file... and for those whom google wasn't helping with how you specify DOCKERCLI.

here's mine:
`services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic
    container_name: borgmatic
    volumes:
      - ${VOLUME_SOURCE}:/mnt/source:ro            # backup source
      - ${VOLUME_TARGET}:/mnt/borg-repository      # backup target
      - ${VOLUME_ETC_BORGMATIC}:/etc/borgmatic.d/  # borgmatic config file(s) + crontab.txt
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg   # config and keyfiles
      - ${VOLUME_SSH}:/root/.ssh                   # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg     # checksums used for deduplication
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
      - DOCKERCLI=true
`

**Comment by Bubbelb** [comment]
Documentation now part of standard README.md, as done with #367 (although the title of the PR does not reflect that, it still is the correct PR/merge)
