### ISSUE TITLE
Deprecated path /root/.borgmatic is still being used. At least for checks

### ISSUE THREAD

**Issue by Bubbelb** [borgmatic-collective/docker-borgmatic#357]
Hi there,

The path /root/.borgmatic is deemed deprecated in the documentation. But the repository and archive check data (timestamps?) are still being stored there.

As a result, when I do not make /root/.borgmatic permanent in my compose.yaml, every repository/archive is being checked, every time the container is renewed, instead of the intervals described in the backup yaml file.

Guess the README.md should be updated...

**Comment by witten** [comment]
Related / possible dup: #211.

**Comment by Bubbelb** [comment]
Ah, overlooked #211. Yup, it is an exact duplicate.
