### ISSUE TITLE
[Errno 18] Cross-device link: '/root/.borgmatic/checks' -> '/root/.local/state/borgmatic/checks'

### ISSUE THREAD

**Issue by Bubbelb** [borgmatic-collective/docker-borgmatic#363]
As per Borgmatic  v1.9.0 state/check files are relocated. It seems Borgmatic wants to hardlink the old location to the new location.

When the path ``/root/.borgmatic`` is set to be a separate volume (as it is, since it is defined in the Dockerfile), Borgmatic will protest with the above error message.

The path in the Docker file and in the documentation should be updated.

This is directly related to #362 and will be solved there. I created this issue for reference, so others can quickly search on the error message.

**Comment by witten** [comment]
It's actually not a hard link.. It's "just" a directory move. But borgmatic 1.9.1 has been released with a fix to support moving the files across filesystems, which is what's breaking here. Note that it's not yet packaged into a container though, so keep an eye out for that.

But updating the docs is great.. Thank you!

**Comment by Bubbelb** [comment]
Update to docker-borgmatic v1.9.1 fixed it. Backup runs fine again.
