### ISSUE TITLE
Replace VOLUME statements

### ISSUE THREAD

**Issue by hr87** [borgmatic-collective/docker-borgmatic#83]
My setup uses a borgmatic container in each stack, taking care of backing up the data for only that stack. Some stack only require a database to be backed up, so I don't need to mount data volumes for borgmatic. The `VOLUME` statement creates anonymous volumes for each borgmatic container.

According to  [this](https://stackoverflow.com/questions/41935435/understanding-volume-instruction-in-dockerfile) , the `VOLUME` statements are not necessary to be able to mount a folders/volumes in the container. However, they create unnamed volumes. So in my case, running several borgmatic images, I have many unused anonymous volumes created by borgmatic.

I suggest replacing them with `mkdir` commands. This ensures the locations are available, but does not create unnecessary volumes. Mounting volumes from the host still works as before. The only difference is, in a case where no explicit volume has been mounted, the data is lost after the container stops. But since in the compose file all of these are explicitly mounted, this is not a problem.

**Comment by hr87** [comment]
I can do a patch, if you agree with this

**Comment by b3vis** [comment]
I agree, I believe the original thought process was creating the volumes within the container would stop people losing data but if there's a better reason to remove then lets remove them.

**Comment by MarkJonas** [comment]
Would it be a compromise to use a named volume?

```
version: '3'
services:
  testomat:
    image: ubuntu:focal
    container_name: testomat
    volumes:
      - testvol:/mnt/testvol:ro

volumes:
  testvol:
```

In that case if the volume is passed with a local path that will be used. If not, a named volume will be created. So no data is lost and yet there are no unnamed, hard to identify volumes flying around.

```
# result when docker-compose.yaml is in directory testomat
$ docker volume ls
DRIVER    VOLUME NAME
local     testomat_testvol
```

I am using that technique in https://gitlab.com/toertel/docker-image-logitech-media-server .

**Comment by rcdailey** [comment]
This should certainly be reopened. I just observed about 50 orphaned volumes with no legible names because of this.

My concern are the deprecated volumes, such as `/root/.borgmatic`, which still have a `VOLUME` directive in the `Dockerfile`. Those should certainly be removed, as the user is already instructed to *not* map those.
