### ISSUE TITLE
Using docker in docker to stop and restart containers before/after backup

### ISSUE THREAD

**Issue by fschrempf** [borgmatic-collective/docker-borgmatic#86]
I'm using docker-borgmatic to backup volumes of several other containers. To get consistent data during the backup, I would like to stop the containers in the `before_backup` hook and restart them in the `after_backup` hook.

To do this I need to run docker in docker which shouldn't be a problem if the docker engine would be installed in the image. Is this something that could be added or are there any objections?

**Comment by b3vis** [comment]
I think adding docker to this image is slightly out of scope. Id suggest looking if portainer or some other docker engine interface could accept a webhook to stop/start your containers

**Comment by fschrempf** [comment]
@toastie89 @b3vis Ok, got it. After looking at the capabilities of the Docker Engine API, the easiest way would probably be to mount the docker socket from the host into the backup container and do API requests to the socket. The problem here is that alpine has none of the common CLI utils like `curl`, `nc -U` or `socat` to send requests to a socket. Would adding `curl` be in scope? :wink:

**Comment by toastie89** [comment]
@fschrempf, from what I see nc is part of busybox, would this do the job?
```
docker run -it --rm b3vis/borgmatic nc
BusyBox v1.31.1 () multi-call binary.

Usage: nc [OPTIONS] HOST PORT  - connect
nc [OPTIONS] -l -p PORT [HOST] [PORT]  - listen
```

**Comment by fschrempf** [comment]
> @fschrempf, from what I see nc is part of busybox, would this do the job?

Hm, at first I thought that it doesn't work, as the busybox `netcat` is missing the `-U` option to connect to a unix socket. But after some more investigation [I found out that using `local:` does the same](https://unix.stackexchange.com/a/554330/331732). This made me come up with the following commands to stop/start my containers from a hook without any additional tools:

```shell
echo -ne "POST /v1.41/containers/<container_id_or_name>/stop HTTP/1.1\r\nHost: localhost\r\n\r\n" | nc local
:/var/run/docker.sock 80
echo -ne "POST /v1.41/containers/<container_id_or_name>/start HTTP/1.1\r\nHost: localhost\r\n\r\n" | nc local
:/var/run/docker.sock 80
```

As this seems to do the job quite well, I consider this solved. Thanks for the help!

**Comment by fschrempf** [comment]
> @fschrempf, nice! Possibly this example could be added to the README?

See #88 for a short documentation of my approach.

**Comment by fschrempf** [comment]
@gjgress Did you try the [example in the README](https://github.com/borgmatic-collective/docker-borgmatic?tab=readme-ov-file#starting-and-stopping-containers-from-hooks) and put in your proxy as host and tcp socket?

**Comment by gjgress** [comment]
I don't see anything in the README which discusses connecting a proxy as host and tcp socket. I've never used a proxy for tcp socket so I'm not even sure where to begin.

I ended up running borgmatic on the host system anyway, which I think makes more sense for my use-case. So my issue is now moot I suppose
