### ISSUE TITLE
Save borgmatic logs to persistent disk?

### ISSUE THREAD

**Issue by karan** [borgmatic-collective/docker-borgmatic#87]
Currently, doesn't seem like borgmatic or borg logs are printed on stdout or persisted on disk anywhere. This would be a good to have in case of failed backups.

**Comment by toastie89** [comment]
@karan, sending logs to stdout is the docker default. You might want to take a look here https://docs.docker.com/engine/reference/commandline/logs/ to learn how to obtain logs.
