### ISSUE TITLE
crond: user root: parse error

### ISSUE THREAD

**Issue by raph-topo** [borgmatic-collective/docker-borgmatic#92]
Hello,
I used the following line in `borgmatic.d/crontab.txt`:
```
0 6 * * 7 /usr/bin/borgmatic prune --stats -v0 2>&1
```
Yet it runs every day! Docker logs also show: `crond: user root: parse error at 7`

`crontab -e` inside the container does not signal a syntax error and the health-check pings supported by Borgmatic do not (!) report this, as Borgmatic did not even start.
But apparently 7 for Sunday is non-standard, and some cron schedule expression tools online do not mention that, instead allowing for a clean 7 as Sunday.

It does not appear to me that this is an issue of Borgmatic, but rather of the Docker image on which docker-borgmatic is based. Maybe a warning in the docs should make sense?

**Comment by b3vis** [comment]
0 6 * * 0 - is what's valid for 6am every Sunday - have you tried this?

**Comment by raph-topo** [comment]
Yes, `0 6 * * 0` works. The only real issue here is that there is no obvious indication this cron won't understand 7 for SUN (neither docs nor vocal error message).

**Comment by b3vis** [comment]
Because it’s non standard? The container is based on Alpine Linux, so not some random weird distribution. It did tell you it had a parse error, there’s nothing to fix here so I’m closing this ticket
