### ISSUE TITLE
Adding findmnt to the image

### ISSUE THREAD

**Issue by kirilldem** [borgmatic-collective/docker-borgmatic#94]
I'm using this container in unraid to set up backups to an intermittently connected external drive. Following the borgmatic docs, I'm trying to probe for the drive using findmnt, however when I run it in the container I get `findmnt: not found`.

`hooks:
    before_backup:
        - findmnt /mnt/disks/Seagate_Backup_Plus_Drive > /dev/null || exit 75
        - echo "Starting a backup."`

https://torsion.org/borgmatic/docs/how-to/backup-to-a-removable-drive-or-an-intermittent-server/#soft-failure-command-hooks 

Could you add findmnt to the docker image?

**Comment by b3vis** [comment]
Sure

**Comment by b3vis** [comment]
This has been added via PR #96 and I will tag and release a new docker tag v1.1.17-1.5.23 which will contain this
