### ISSUE TITLE
sshd on borgmatic container?

### ISSUE THREAD

**Issue by Sdub76** [borgmatic-collective/docker-borgmatic#98]
I have 2 docker containers running this borgmatic image that I'd like to be able to back up to each other.   This container has an SSH client but does not appear to have the SSH server component.  

My workaround is to install the borg binary to the OS base image but I'd rather just have the 2 docker containers talk directly to each other.

Is there a way to add this without the openssh server being added to the docker image?

**Comment by b3vis** [comment]
Hi I’ve been thinking about this one and I think it’s out of the scope of this project. 

I wrote this years ago to solve the problem you have, it’s kinda old and probably not as good as it could be but check out https://github.com/b3vis/borg-server

**Comment by Sdub76** [comment]
I was giving this some more thought... could you edit your config.yaml file and add the line:

```
# Alternate Borg remote executable. Defaults to "borg".
    remote_path: ssh root@192.168.1.2 docker exec borgmatic borg
```

Where 192.168.1.2 is the IP of the server that you're trying to backup to?  As long as the host running docker has a working SSH config it seems like this might work.

**Comment by Sdub76** [comment]
Actually, I take that back... that would be redundant to the SSH command that's built in for remote repos...

   repositories:
        - 192.168.1.2:/borg_repo
   remote_path: docker exec borgmatic borg
`

**Comment by Sdub76** [comment]
Didn't work...  I think the nature of how docker exec commands execute doesn't allow the executable to continue running.  

with "docker exec borgmatic borg", I got:
```
192.168.1.2:/borg-repo: Error running actions for repository
Got unexpected RPC data format from server:
Borg 1.1.17: Got connection close before repository was opened.
````

with "docker exec -it borgmatic borg", I got:
```
192.168.1.2:/borg-repo: Error running actions for repository
Remote: the input device is not a TTY
Connection closed by remote host. Is borg working on the server?
````

with "docker exec -t borgmatic borg", I got: 
```
192.168.1.2:/borg-repo: Error running actions for repository
Connection closed by remote host. Is borg working on the server?
````

Figured it was worth putting here in case someone else searches for the same, or has a better idea.
